name = "kronos-api"
compatibility_date = "2025-01-01"

routes = {
  {pattern = "kronos-api.izzatfaris.site"}
}

[dev]
ip = "0.0.0.0"
port = 4305

[observability.logs]
enabled = true

# [vars]
# MY_VARIABLE = "production_value"
[[kv_namespaces]]
binding = "kronos"
id = "random-id"
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
